myBlog/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.views import static

from blog.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login),
    path('logout/', logout),
    path('register/', register),

    path('query_article_list/', query_article_list, name="article"),
    path('query_tag_list/', query_tag_list, name="tag"),
    path('query_cate_list/', query_cate_list, name="cate"),
    path('query_month_list/', query_month_list, name="month"),
    path('query_comment_list/', query_comment_list, name="comment"),
    # 处理点赞
    path('dig/', dig, name="dig"),
    # 处理评论
    path('comment/', comment, name="comment_sm"),

    path("default_settings/", default_settings, name="default_settings"),
    re_path("^article/(?P<article_id>\d+)\.html/$", article, name="article"),

    path('about/', about),
    re_path('^$', index),
    path("get_validCode_img/", get_ValidCode_img),

    # media配置
    re_path(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT}),

    re_path('^(?P<htmlname>.*?\.html)/$', other),
    # 用户站点
    re_path('^(?P<site_name>\w+)/$', home_site),

    re_path(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}),

]

blog/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.

class UserInfo(AbstractUser):
    """用户信息"""
    nid = models.AutoField(primary_key=True, )
    telephone = models.CharField(max_length=11, null=True, unique=True, )
    # 存储用户头像文件
    avatar = models.FileField(upload_to='avatars/', default="avatars/default.png")
    # 在生成字段时就以当前时间存储，用于计算园龄
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    # 业务分离,用户名下blog删除，则站点blog同时删除
    blog = models.OneToOneField(to='Blog', to_field='nid', null=True, on_delete=models.PROTECT,
                                related_name="UserInfo_blog")

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = verbose_name_plural = "用户信息"


class Blog(models.Model):
    """
    博客信息表---站点表
    1. 直接继承自UserInfo的nid，同时拒绝删除外键，设置自增减
    """
    # nid = models.OneToOneField(to='UserInfo', to_field='nid', on_delete=models.PROTECT, parent_link=True, primary_key=True,
    #                            related_name='Blog_nid')
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='个人博客标题', max_length=64)
    # https://home.cnblogs.com/u/1915559/，对应这部分[u/1915559/]
    site_name = models.CharField(verbose_name='站点名称', max_length=64)
    # 一套CSS文件
    theme = models.CharField(verbose_name='博客主题', max_length=32)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = verbose_name_plural = "博客信息"


class Category(models.Model):
    """博主个人文章分类表"""
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题', max_length=32)
    # 分类表下的blog删除之后，整篇blog也会删除，因此设置级联删除
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid', on_delete=models.CASCADE,
                             related_name='Category_blog', db_column='blog')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = verbose_name_plural = "用户信息"


class Tag(models.Model):
    """
    标签
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称', max_length=32)
    # on_delete=models.PROTECT 标签被删除，外键关联的blog不能被删除
    # to_field='nid' 关联对象的字段名称，该字段必须是unique=True
    # related_name 指定用于反向查询的对象, 如果两个对象继承自同一个类，重命名之后则不再因为反向查询而冲突
    # 标签表下的blog删除之后，整篇blog也会删除，因此设置级联删除
    blog_id = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid', on_delete=models.CASCADE,
                                related_name='Article', db_column='blog_nid')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = verbose_name_plural = "标签"


class Article(models.Model):
    """
    文章表
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50, verbose_name='文章标题')
    # desc 是description---摘要
    desc = models.CharField(max_length=255, verbose_name='文章描述')
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    comment_count = models.IntegerField(default=0, verbose_name="评论数")
    up_count = models.IntegerField(default=0, verbose_name="点赞数")
    down_count = models.IntegerField(default=0, verbose_name="点踩数")

    # 文章表下的用户删除之后，原来的用户信息也会删除，因为文章表必须要有作者
    user = models.ForeignKey(verbose_name='作者', to='UserInfo', to_field='nid', on_delete=models.CASCADE,
                             related_name='Article_user', db_column='user')
    # 文章下对分类的删除也会对分类主表进行删除
    category = models.ForeignKey(verbose_name="文章分类", to='Category', to_field='nid', null=True,
                                 on_delete=models.CASCADE,
                                 related_name='Article_category', db_column='category')
    tags = models.ManyToManyField(

        to="Tag",  # to 参数用来指定与当前model类关联的model类
        through='Article2Tag',
        through_fields=('article', 'tag')
    )
    content = models.TextField(verbose_name="正文")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = verbose_name_plural = "文章表"


class Article2Tag(models.Model):
    """
    文章表与标签表的中间表
    仅仅添加了一个新的ID，用于给两个表内容进行定位
    一旦文章表或者标签表删除，则与他们关联的ID则删除，称为级联删除
    """
    nid = models.AutoField(primary_key=True)
    # 标签和文章的关联，属于多对多关系，标签可以删除，表不能删除，所以外键关联
    # 中间表相当于对两张表的引用，因此删除也需要同步
    article = models.ForeignKey(verbose_name='文章', to="Article", to_field='nid', on_delete=models.CASCADE)
    tag = models.ForeignKey(verbose_name='标签', to="Tag", to_field='nid', on_delete=models.CASCADE)

    class Meta:
        # 联合唯一，字段不能重复
        unique_together = [
            ('article', 'tag'),
        ]

        verbose_name = verbose_name_plural = "文章表与标签表的中间表"

    def __str__(self):
        v = self.article.title + "---" + self.tag.title
        return v


class ArticleUpDown(models.Model):
    """
        点赞表
        如果点赞被删除，那么用户表和文件表不会被删除
    """
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey(to='UserInfo', null=False, on_delete=models.PROTECT, default=None)
    article = models.ForeignKey(to="Article", null=False, on_delete=models.PROTECT, default=None)
    is_up = models.BooleanField(default=True)

    class Meta:
        unique_together = [
            ('article', 'user')
        ]

        verbose_name = verbose_name_plural = "点赞表"


class Comment(models.Model):
    """评论表"""
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey(verbose_name='评论者', to='UserInfo', to_field='nid', on_delete=models.PROTECT)
    article = models.ForeignKey(verbose_name='评论文章', to='Article', to_field='nid', on_delete=models.PROTECT)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    # 富文本编辑器 ckeditor
    # body = RichTextField()
    content = models.TextField(verbose_name='评论内容')
    # self == Comment: 数据库语法自关联
    parent_comment = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, verbose_name='评论对象', )

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = verbose_name_plural = "评论表"

blog/views.py
import json

from django.conf import settings
from django.contrib import auth
from django.db.models import Count
from django.db.models import F
from django.db.models.functions import TruncMonth
from django.http import JsonResponse
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.template.loader import get_template

from .models import *


# Create your views here.


def index(request):
    return render(request, "Tale/base.html", {"user": {"username": settings.ALL_USER}})
    # html = '<h1>标题</h1>'
    # return render(request, "test.html", {"html": html})


def about(request):
    article_list = Article.objects.all()

    # return render(request, "blog/index.html", {"article_list": article_list})
    return render(request, "Tale/about.html", )


def other(request, htmlname):
    # article_list = Article.objects.all()
    template_name = f"Tale/{htmlname}"
    # return render(request, "blog/index.html", {"article_list": article_list})
    return render(request, template_name=template_name, )


# 登录
def login(request):
    """登录"""

    if request.is_ajax():
        response = {"user": None, "msg": None, "code": None}
        user = request.POST.get("user")
        pwd = request.POST.get("pwd")

        # 检验验证码

        user = auth.authenticate(username=user, password=pwd)
        if user:
            auth.login(request, user)  # request.user==当前登录对象
            response['user'] = user.username
            response['code'] = 1

        else:
            response['msg'] = "用户名密码错误!"
            response['code'] = -1

        return JsonResponse(response)

    return render(request, 'login_out/index.html')


# 用户注销

def logout(request):
    auth.logout(request)  # request.session.flush()
    referer_url = request.headers.get("Referer")
    if referer_url:
        return HttpResponseRedirect(referer_url)
    return HttpResponseRedirect("/")


def get_ValidCode_img(request):
    from .utils.validCode import get_valid_code_img

    data = get_valid_code_img(request)

    return HttpResponse(data)


# 注册
def register(request):
    if request.is_ajax():

        response = {"user": None, "msg": "cuowu", "code": None}
        username = request.POST.get("user")

        pwd = request.POST.get("pwd")
        re_pwd = request.POST.get("re_pwd")

        user = UserInfo.objects.filter(username=username).values()
        if not (username and pwd and re_pwd):
            response['msg'] = "字段不允许为空"

        if not user:
            if pwd == re_pwd:
                response['user'] = username

                user_obj = UserInfo.objects.create_user(username=username, password=pwd, )
            else:
                response['msg'] = "两次密码不一致！"

        else:

            response['msg'] = "账户已经存在"
        return JsonResponse(response)


def home_site(request, site_name):
    """
    个人站点视图函数
    """

    user = UserInfo.objects.filter(blog__site_name=site_name).first()

    # 判断用户是否存在
    if not user:
        return render(request, "blog/not_found.html")
    # 查询当前站点对象
    blog = user.blog
    return render(request, "Tale/author.html",
                  {"user": user, "blog": blog, })


# 查询文章列表
def query_article_list(request):
    """
    查询文章列表
    :param request:
    :return:
    """
    if request.is_ajax():

        id = request.POST.get("id")
        name = request.POST.get("name")
        username = request.POST.get("username")

        if username != settings.ALL_USER:

            if name == 'tag':
                article_list = Article.objects.filter(user__username=username, tags__title=id)
            elif name == "cate":
                article_list = Article.objects.filter(user__username=username, category__title=id)
            elif name == "month":
                year, month = id.split('-')
                article_list = Article.objects.filter(user__username=username).filter(
                    create_time__year=year, create_time__month=month)

            elif name == "all":
                article_list = Article.objects.filter(user__username=username)
            else:
                return JsonResponse({"code": 0})
        else:

            if name == 'tag':
                article_list = Article.objects.filter(tags__title=id)
            elif name == "cate":
                article_list = Article.objects.filter(category__title=id)
            elif name == "month":
                year, month = id.split('-')
                article_list = Article.objects.filter().filter(
                    create_time__year=year, create_time__month=month)
            else:
                article_list = Article.objects.filter()

        t = get_template("Tale/article_list.html")
        content_html = t.render({'article_list': article_list, })

        response = {"content_html": content_html, "code": 1}

        return JsonResponse(response)


# 获取标签列表
def query_tag_list(request):
    """
    查询文章列表
    :param request:
    :return:
    """
    if request.is_ajax():
        # id = request.POST.get("id")
        # name = request.POST.get("name")

        username = request.POST.get("username")
        response = {"content_html": None, "code": 0}
        if username:
            if username != settings.ALL_USER:
                user = UserInfo.objects.filter(username=username).first()

                # 查询当前站点对象
                blog = user.blog
                userid = user.nid
                nid = blog.nid  # 用作原地跳转标签匹配
                # 查询当前站点的每一个标签名称以及对应的文章数
                tag_list = Tag.objects.values('pk').annotate(c=Count("article")).values("title", "c").filter(
                    blog_id=nid)

            else:
                tag_list = Tag.objects.values('pk').annotate(c=Count("article")).values("title", "c")

            t = get_template("Tale/tag_list.html")
            content_html = t.render({'tag_list': tag_list, })

            response = {"content_html": content_html, "code": 1}

        return JsonResponse(response)


# 获取分类列表
def query_cate_list(request):
    """
    获取分类列表
    :param request:
    :return:
    """
    if request.is_ajax():
        # id = request.POST.get("id")
        # name = request.POST.get("name")
        username = request.POST.get("username")
        response = {"content_html": None, "code": 0}
        if username:
            if username != settings.ALL_USER:

                user = UserInfo.objects.filter(username=username).first()

                # 查询当前站点对象
                blog = user.blog
                userid = user.nid
                nid = blog.nid  # 用作原地跳转标签匹配
                # 查询当前站点的每一个标签名称以及对应的文章数
                cate_list = Category.objects.filter(
                    blog__nid=nid).values("title").annotate(c=Count("Article_category"))
            else:
                cate_list = Category.objects.filter().values("title").annotate(c=Count("Article_category"))

            t = get_template("Tale/cate_list.html")
            content_html = t.render({'cate_list': cate_list, })

            response = {"content_html": content_html, "code": 1}

        return JsonResponse(response)


# 获取归档列表
def query_month_list(request):
    """
    获取归档列表
    :param request:
    :return:
    """
    if request.is_ajax():
        username = request.POST.get("username")

        response = {"content_html": None, "code": 0}
        if username:
            if username != settings.ALL_USER:
                user = UserInfo.objects.filter(username=username).first()

                # 查询当前站点对象
                blog = user.blog
                userid = user.nid
                nid = blog.nid  # 用作原地跳转标签匹配
                # 查询当前站点的每一个标签名称以及对应的文章数
                year_month = Article.objects.filter(user=userid).annotate(month=TruncMonth("create_time")).values(
                    "month").annotate(
                    c=Count(nid)).values("month", 'c')
            else:
                year_month = Article.objects.filter().annotate(month=TruncMonth("create_time")).values(
                    "month").annotate(
                    c=Count('nid')).values("month", 'c')

            t = get_template("Tale/year_month.html")
            content_html = t.render({'year_month': year_month, })

            response = {"content_html": content_html, "code": 1}
        return JsonResponse(response)


def article(request, article_id):
    """文章详情页"""
    # 文章
    article = Article.objects.filter(pk=article_id).first()
    # 所属标签
    tags = article.tags.values().first().get("title")
    # 所属分类
    category = article.category.title
    # 日期
    month = article.create_time.date()
    # 作者信息
    article_author = article.user

    return render(request, 'Tale/single-post-minimal.html',
                  {"article": article, "tags": tags, "category": category, "month": f"{month.year}-{month.month}",
                   "article_author": article_author})


# 处理点赞功能
def dig(request):
    """
    处理点赞功能
    :param request:
    :return:
    """
    if request.is_ajax():
        response = {"state": True, "msg": None}
        # id = request.POST.get("id")
        # is_up = request.POST.get("is_up")  # "true"/"false"
        is_up = json.loads(request.POST.get("is_up"))
        article_id = request.POST.get("article_id")
        user_id = request.user.pk
        if user_id:
            obj = ArticleUpDown.objects.filter(user_id=user_id, article_id=article_id).first()
            if not obj:
                ard = ArticleUpDown.objects.create(user_id=user_id, article_id=article_id, is_up=is_up)
                queryset = Article.objects.filter(pk=article_id)
                if is_up:

                    queryset.update(up_count=F("up_count") + 1)
                else:
                    queryset.update(down_count=F("down_count") + 1)
            else:
                response['state'] = False
                response['handed'] = obj.is_up
        else:
            response['state'] = False
            response['msg'] = "您尚未登录，请先<a href='/login/'>登录</a>"

templates/blog/base.html
<!DOCTYPE html>
{% load static %}
{% load cache %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {#    <title>个人站点表</title>#}
    <link rel="stylesheet" href="{% static 'blog/css/home_site.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/article_detail.css' %}">
    <link rel="stylesheet" href="{% static 'blog/bs/css/bootstrap.css' %}">
    <link rel="shortcut icon" href="{% static 'blog/img/user.ico' %}" type="image/x-icon">
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
</head>
<body>

<div class="header">
    <div class="content">
        <p class="title">
            <span>{{ blog.title }}</span>
            <a href="" class="backend">管理</a>
        </p>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-3">
            {% cache 15 hs %}
                {% load my_tags %}
                {% get_classification_style username %}
            {% endcache %}
        </div>
        <div class="col-md-9">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
<div class="container">
    <li> © 2021 <a href="">CaesarTylor</a></li>
    <li> · Powered by <a href="">Django3.2.8</a></li>
</div>
</body>
</html>

templates/blog/home_site.html
<!doctype html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">


    <title>{{ blog.title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="/static/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/blog.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]>
    <script src="/static/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="/static/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<div class="blog-masthead">
    <div class="container">
        <nav class="blog-nav">
            <a class="blog-nav-item active" href="#">Home</a>
            <a class="blog-nav-item" href="#">New features</a>
            <a class="blog-nav-item" href="#">Press</a>
            <a class="blog-nav-item" href="#">New hires</a>
            <a class="blog-nav-item  " href="#">关于</a>
            <a class="blog-nav-item  navbar-right" href="#">管理</a>
        </nav>
    </div>
</div>


<div class="container">

    <div class="blog-header">
        <h1 class="blog-title">{{ blog.title }}</h1>
        <p class="lead blog-description">使用 Bootstrap 创建博客的官方示例模板。</p>
    </div>

    <div class="row">

        <div class="col-sm-8 blog-main">
            <!-- /.blog-post -->
            {% for article in article_list %}
                <div class="blog-post">
                    <h2 class="blog-post-title">{{ article.title }}</h2>
                    <span class="blog-post-meta">2013年12月23日 由 <a href="#">{{  article.user.username }}</a></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <span class="glyphicon glyphicon-comment">评论({{ article.comment_count }})</span>&nbsp;&nbsp;&nbsp;
                    <span class="glyphicon glyphicon-thumbs-up">点赞({{ article.up_count }})</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <p>{{ article.desc }}</p>
                </div>

            {% endfor %}




            <nav>
                <ul class="pager">
                    <li><a href="#">上一个</a></li>
                    <li><a href="#">下一个</a></li>
                </ul>
            </nav>

        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
            <div class="sidebar-module sidebar-module-inset">
                <h4>关于</h4>
                <p>埃蒂亚姆 · 波尔塔· 塞姆 · 马莱苏达 · 马格纳 ·莫利斯 · 尤斯莫德克拉斯 · 马蒂斯 · 康塞特 · 普鲁斯坐在一个美特发酵。埃尼安 · 莱西尼亚 · 比本杜姆 · 努拉 · 塞德 ·
                    塞斯特。</p>
            </div>
            <div class="sidebar-module">
                <h4>档案</h4>
                <ol class="list-unstyled">
                    <li><a href="#">2014 年 3 月</a></li>
                    <li><a href="#">2014 年 2 月</a></li>
                    <li><a href="#">2014 年 1 月</a></li>
                    <li><a href="#">2013 年 12 月</a></li>
                    <li><a href="#">2013 年 11 月</a></li>
                    <li><a href="#">2013 年 10 月</a></li>
                    <li><a href="#">2013 年 9 月</a></li>

                </ol>
            </div>
            <div class="sidebar-module">
                <h4>友链</h4>
                <ol class="list-unstyled">
                    <li><a href="#">GitHub</a></li>
                    <li><a href="#">Twitter</a></li>
                    <li><a href="#">Facebook</a></li>
                </ol>
            </div>
        </div><!-- /.blog-sidebar -->

    </div><!-- /.row -->

</div><!-- /.container -->

<footer class="blog-footer">
    <p>博客模板建立的<a href="https://getbootstrap.com/">Bootstrap</a> 由 <a href="https://twitter.com/mdo">@mdo</a>.
    </p>
    <p>
        <a href="#">回到顶部</a>
    </p>
</footer>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/static/js/jquery-3.6.0.min.js"
        integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="/static/js/jquery.min.js"><\/script>')</script>
<script src="/static/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="/static/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>

templates/blog/home_site1.html
<!doctype html>
<html lang="zh">
<head>
    <meta charset="UTF-8">

    <title>Document</title>
    <style>
        * {
            margin: 0;
            padding: 0;
        }

        .header {
            width: 100%;
            height: 60px;
            background-color: #369;
        }

        .header .title {
            font-size: 18px;
            font-weight: 100;
            line-height: 60px;
            color: white;
            margin-left: 15px;
        }
    </style>
</head>
<body>

<div class="header">
    <div class="content">
        <p class="title">{{ blog.title }}</p>

    </div>
</div>


</body>
</html>

templates/blog/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>注册</title>
    <link rel="stylesheet" href="/static/css/bootstrap.css">
    <style>
        #avatar_img {
            margin-left: 20px;
        }

        #avatar {
            display: none;
        }

        .error {
            color: red;
        }
    </style>
    <!--    <link rel="stylesheet" href="D:\Django学习\myBlog\static\blog\bs\css\bootstrap.css">-->

</head>

<body>

<h3>欢迎注册</h3>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-lg-offset-3">

            <form id="form">
                {% csrf_token %}

                <!--渲染表单-->
                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.auto_id }}">{{ field.label }}</label> {{ field }}
                        <span class="error pull-right"></span>
                    </div>
                {% endfor %}
                <!--头像-->
                <div class="form-group">
                    <br>
                    <label for="avatar">
                        头像
                        <img id="avatar_img" width="40" height="40" src="/static/img/default.png" alt="">
                    </label>

                    <input type="file" id="avatar" accept="image/*" >
                    {# <input type="file" id="avatar" accept="image/gif,image/jpeg,image/jpg,image/png,image/svg"> #}
                </div>

                <br>
                <input type="button" class="btn btn-success reg_btn pull-left" value="注册">
                <!--  <input type="button" class="btn btn-default login_btn glyphicon-log-in"> -->

            </form>

        </div>


    </div>
</div>
<script src="/static/js/jquery-3.6.0.min.js"></script>
<script>
    // 头像预览
    $("#avatar").change(
        function () {
            // 获取一户选中的文件对象
            var file_boj = $(this)[0].files[0];

            // 获取文件对象的路径
            var reader = new FileReader();

            reader.readAsDataURL(file_boj);
            reader.onload = function () {
                $("#avatar_img").attr("src", reader.result);
            }
            //修改imgsrc属性，src=文件对象的路径


        }
    )


    // 基于ajax提交数据
    $(".reg_btn").click(function () {

        var form_data = new FormData();
        //获取表单数据
        console.log($("#form").serializeArray())
        var request_data = $("#form").serializeArray();

        $.each(request_data, function (index, data) {
            form_data.append(data.name, data.value)
        })


        form_data.append("user", $("#id_user").val());

        // form_data.append("pwd", $("#id_pwd").val());
        // form_data.append("re_pwd", $("#id_re_pwd").val());
        // form_data.append("email", $("#id_email").val());
        // form_data.append("csrfmiddlewaretoken", $("[name='csrfmiddlewaretoken']").val());

        form_data.append("avatar", $("#avatar")[0].files[0]);


        $.ajax({
            url: "",
            type: "post",

            // 有FormData，需要添加以下参数，不然报错
            contentType: false,
            processData: false,

            data: form_data,
            success: function (data) {
                console.log(data);

                $("span.error").html("") //清空提示
                $(".form-group").removeClass("has-error"); //清除输入框变红
                if (data.user) {
                    // 注册成功
                    location.href = "/login/"
                } else {


                    // 展示此次提交错误信息！
                    $.each(data.msg, function (field, error_list) {
                        console.log(field, error_list);
                        // 两次密码不一样
                        if (field === "__all__") {
                            $("#id_re_pwd").next().html(error_list[0]);
                            $("#id_re_pwd").parent().addClass("has-error")
                        }
                        // 注册失败

                        $("#id_" + field).next().html(error_list[0]); //错误提示
                        $("#id_" + field).parent().addClass("has-error"); //错误框变红
                    })
                }

            }

        })
    })
</script>

</body>

</html>